# From https://github.com/simonw/git-scraper-template/blob/main/.github/workflows/scrape.yml
name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
  # Daily at 6:23 AM UTC
  - cron: '23 6 * * *'
  # For hourly at 42 minutes past the hour: '42 * * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run the scraper
      run: |
        ./resources/download.sh
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "chore: update source schedule JSON" || exit 0
        git pull --rebase
        git push
